In [2]:
import numpy as np 
import pandas as pd

In [3]:
DATASET = ["netflix", "amazon_prime", "disney_plus"][2]
movies = pd.read_csv(f'../data/{DATASET}_titles.csv')

In [4]:
movies.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...

In [5]:
movies = movies[['title','director','cast','country','date_added','release_year', 'listed_in', 'description']]

In [6]:
movies.head(2)

,title,director,cast,country,date_added,release_year,listed_in,description
0,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,Comedy,Santa Claus passes his magic bag to a new St. ...

In [7]:
movies.isnull().sum()

title             0
director        473
cast            190
country         219
date_added        3
release_year      0
listed_in         0
description       0
dtype: int64

In [8]:
movies.duplicated().sum()

0

In [9]:
movies = movies.apply(lambda x: x.map(lambda v: v.lower() if isinstance(v, str) else v))

In [10]:
movies.head(2)

,title,director,cast,country,date_added,release_year,listed_in,description
0,duck the halls: a mickey mouse christmas special,"alonso ramirez ramos, dave wasson","chris diamantopoulos, tony anselmo, tress macn...",NaN,"november 26, 2021",2016,"animation, family",join mickey and the gang as they duck the halls!
1,ernest saves christmas,john cherry,"jim varney, noelle parker, douglas seale",NaN,"november 26, 2021",1988,comedy,santa claus passes his magic bag to a new st. ...

In [11]:
def split_str(x):
    if isinstance(x, str):
        return x.split(",")
    else:
        return []

In [12]:
movies['director'] = movies['director'].apply(split_str)
movies['cast'] = movies['cast'].apply(split_str)
movies['country'] = movies['country'].apply(split_str)
movies['listed_in'] = movies['listed_in'].apply(split_str)

In [13]:
movies.head(2)

,title,director,cast,country,date_added,release_year,listed_in,description
0,duck the halls: a mickey mouse christmas special,"[alonso ramirez ramos, dave wasson]","[chris diamantopoulos, tony anselmo, tress m...",[],"november 26, 2021",2016,"[animation, family]",join mickey and the gang as they duck the halls!
1,ernest saves christmas,[john cherry],"[jim varney, noelle parker, douglas seale]",[],"november 26, 2021",1988,[comedy],santa claus passes his magic bag to a new st. ...

In [14]:
def remove_space(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [15]:
movies["platform"] = [DATASET for i in range(len(movies))]

In [16]:
# movies['director'] = movies['director'].apply(remove_space)
# movies['cast'] = movies['cast'].apply(remove_space)
# movies['listed_in'] = movies['listed_in'].apply(remove_space)

In [17]:
movies.head(1000)

,title,director,cast,country,date_added,release_year,listed_in,description,platform
0,duck the halls: a mickey mouse christmas special,"[alonso ramirez ramos, dave wasson]","[chris diamantopoulos, tony anselmo, tress m...",[],"november 26, 2021",2016,"[animation, family]",join mickey and the gang as they duck the halls!,disney_plus
1,ernest saves christmas,[john cherry],"[jim varney, noelle parker, douglas seale]",[],"november 26, 2021",1988,[comedy],santa claus passes his magic bag to a new st. ...,disney_plus
2,ice age: a mammoth christmas,[karen disher],"[raymond albert romano, john leguizamo, deni...",[united states],"november 26, 2021",2011,"[animation, comedy, family]",sid the sloth is on santa's naughty list.,disney_plus
3,the queen family singalong,[hamish hamilton],"[darren criss, adam lambert, derek hough, a...",[],"november 26, 2021",2021,[musical],"this is real life, not just fantasy!",disney_plus
4,the beatles: get back,[],"[john lennon, paul mccartney, george harriso...",[],"november 25, 2021",2021,"[docuseries, historical, music]",a three-part documentary from peter jackson ca...,disney_plus
...,...,...,...,...,...,...,...,...,...
995,kronk's new groove,"[elliot bour, saul blinkoff]","[patrick warburton, tracey ullman, eartha ki...",[united states],"november 12, 2019",2005,"[animation, comedy, coming of age]",kronk cooks up a get-rich-quick scheme to impr...,disney_plus
996,la luna,[enrico casarosa],"[tony fucile, krista sheffler, phil sheridan]",[united states],"november 12, 2019",2012,"[animation, coming of age, family]",a peculiar story about a young boy coming of age.,disney_plus
997,lab rats,[],"[billy unger, spencer boldman, kelli berglun...",[united states],"november 12, 2019",2011,"[action-adventure, comedy, coming of age]",leo discovers a secret underground lab with th...,disney_plus
998,lady and the tramp,[charlie bean],"[tessa thompson, justin theroux, sam elliott...",[united states],"november 12, 2019",2019,"[action-adventure, comedy, family]",a house dog and a stray embark on an adventure...,disney_plus
999,lava,[james murphy],"[kuana kahele, napua greig]",[united states],"november 12, 2019",2015,"[animation, family, musical]",a love story that takes place over millions of...,disney_plus

In [18]:
def process_title(s):
    result = s.split(":")[0].strip()
    result = result.split("-")[0].strip()
    return result

In [19]:
print(process_title("Go! Go! Cory Carson: Chrissy Takes the Wheel"))

Go! Go! Cory Carson

In [20]:
movies['title'] = movies['title'].apply(process_title)

In [21]:
movies

,title,director,cast,country,date_added,release_year,listed_in,description,platform
0,duck the halls,"[alonso ramirez ramos, dave wasson]","[chris diamantopoulos, tony anselmo, tress m...",[],"november 26, 2021",2016,"[animation, family]",join mickey and the gang as they duck the halls!,disney_plus
1,ernest saves christmas,[john cherry],"[jim varney, noelle parker, douglas seale]",[],"november 26, 2021",1988,[comedy],santa claus passes his magic bag to a new st. ...,disney_plus
2,ice age,[karen disher],"[raymond albert romano, john leguizamo, deni...",[united states],"november 26, 2021",2011,"[animation, comedy, family]",sid the sloth is on santa's naughty list.,disney_plus
3,the queen family singalong,[hamish hamilton],"[darren criss, adam lambert, derek hough, a...",[],"november 26, 2021",2021,[musical],"this is real life, not just fantasy!",disney_plus
4,the beatles,[],"[john lennon, paul mccartney, george harriso...",[],"november 25, 2021",2021,"[docuseries, historical, music]",a three-part documentary from peter jackson ca...,disney_plus
...,...,...,...,...,...,...,...,...,...
1445,x,[gavin hood],"[hugh jackman, liev schreiber, danny huston,...","[united states, united kingdom]","june 4, 2021",2009,"[action-adventure, family, science fiction]",wolverine unites with legendary x-men to fight...,disney_plus
1446,night at the museum,[shawn levy],"[ben stiller, amy adams, owen wilson, hank ...","[united states, canada]","april 2, 2021",2009,"[action-adventure, comedy, family]",larry daley returns to rescue some old friends...,disney_plus
1447,eddie the eagle,[dexter fletcher],"[tom costello, jo hartley, keith allen, dic...","[united kingdom, germany, united states]","december 18, 2020",2016,"[biographical, comedy, drama]","true story of eddie edwards, a british ski-jum...",disney_plus
1448,bend it like beckham,[gurinder chadha],"[parminder nagra, keira knightley, jonathan ...","[united kingdom, germany, united states]","september 18, 2020",2003,"[buddy, comedy, coming of age]",despite the wishes of their traditional famili...,disney_plus
1449,captain sparky vs. the flying saucers,[mark waring],[charlie tahan],[united states],"april 1, 2020",2012,"[action-adventure, animals & nature, animation]",view one of sparky's favorite home movies.,disney_plus

In [79]:
movies.to_csv(f'../data/{DATASET}_titles_preprocessed.csv', index=False)

In [25]:
DATASET = ["netflix", "amazon_prime", "disney_plus"]
netflix_df, prime_df, disney_df = [pd.read_csv(f'../data/{_}_titles_preprocessed.csv') for _ in DATASET]
big_df = pd.concat([netflix_df, prime_df, disney_df], axis=0)

# Optionally, reset the index if you want a fresh index for the combined DataFrame
big_df.reset_index(drop=True, inplace=True)

big_df.info()

big_df.to_csv(f'../data/all_plattforms_titles_preprocessed.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19925 entries, 0 to 19924
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         19925 non-null  object
 1   director      19925 non-null  object
 2   cast          19925 non-null  object
 3   country       19925 non-null  object
 4   date_added    10399 non-null  object
 5   release_year  19925 non-null  int64
 6   listed_in     19925 non-null  object
 7   description   19925 non-null  object
 8   platform      19925 non-null  object
dtypes: int64(1), object(8)
memory usage: 1.4+ MB